# Generated by Django 5.1.7 on 2025-03-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('review_score', models.FloatField()),
                ('ranking_in_category', models.IntegerField()),
                ('installation_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_make', models.CharField(max_length=255)),
                ('device_model', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=50)),
                ('os_release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DataPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_collected_linked_to_you', models.JSONField(default=list)),
                ('data_collected_not_linked_to_you', models.JSONField(default=list)),
                ('permissions_asked_for', models.JSONField(default=list)),
                ('permissions_granted', models.JSONField(default=list)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.app')),
            ],
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('battery', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('memory', models.CharField(max_length=50)),
                ('storage_available', models.CharField(max_length=50)),
                ('network_type', models.CharField(max_length=50)),
                ('io_received', models.CharField(max_length=50)),
                ('io_sent', models.CharField(max_length=50)),
                ('access_information', models.JSONField(default=list)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
    ]
