# Generated by Django 5.1.7 on 2025-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_app_device_datapermissions_usagestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='recommended_age_range',
            field=models.CharField(default='Not Available', max_length=50),
            preserve_default=False,
        ),
    ]
