# Generated by Django 5.1.7 on 2025-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_app_recommended_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='recommended_age_range',
            field=models.CharField(default='Not Available', max_length=50),
        ),
    ]
